#!/bin/sh

UPLOADSCRIPT=imgscp

## make temp file
THING=$(mktemp --suffix=.png)
chmod +r "${THING}"

## take screen shot
scrot -s "${THING}"

echo -n "hold on " | xclip

## upload screen shot
$UPLOADSCRIPT "${THING}"
