#!/bin/sh

if [ "$#" -lt 1 -o ! -f "$1" ]; then
  echo "usage: $0 <file>" 1>&2
  exit 1
fi

THING="$1"
SSHSTR="pompom"
BLAH=$(sha1sum "${THING}" | awk '{ print $1 }')

scp "${THING}" "${SSHSTR}:scrots/${BLAH}.png"

if [ $? -ne 0 ]; then
  echo error 1>&2
  exit 1
fi

IMGURL="http://omgren.com/s/${BLAH}.png"
echo $IMGURL
