#!/bin/sh

if [ "$#" -lt 1 -o ! -f "$1" ]; then
  echo "usage: $0 <file>" 1>&2
  exit 1
fi

THING=$1
KEY=PUT_YOUR_API_KEY_HERE
URL=http://imgur.com/api/upload.xml
OUTPUT=/tmp/imgur.xml

if [ -f $THING ]; then
  curl -o $OUTPUT -s -F "image=@${THING}" -F "key=${KEY}" "${URL}"
else
  curl -o $OUTPUT -s -d "image=${THING}" -d "key=${KEY}" "${URL}"
fi

if [ $? -ne 0 ]; then
  echo error 1>&2
  exit 1
fi

IMGURL=$(perl -nle 'print $1 if /original_image.(http.+?\.png)/' $OUTPUT)
echo $IMGURL
