#!/bin/sh

## imgur anonymous api key infomration available
## here: http://api.imgur.com/resources_anon#upload

KEY=PUT_YOUR_API_KEY_HERE

if [ "$#" -lt 1 ]; then
  echo "usage: $0 <file or image url>" 1>&2
  exit 1
fi

## either a path to file or url to image
THING=$1

URL=http://api.imgur.com/2/upload.xml
OUTPUT=/tmp/imgur.xml

## if $THING is a path to a file, then upload the file
## or else assume $THING is a url and have imgur sideload
## that url

if [ -f $THING ]; then
  curl -o $OUTPUT -s -F "image=@${THING}" -F "key=${KEY}" "${URL}"
else
  curl -o $OUTPUT -s -d "image=${THING}" -d "key=${KEY}" "${URL}"
fi

if [ $? -ne 0 ]; then
  echo error 1>&2
  exit 1
fi

IMGURL=$(perl -nle 'print $1 if /original>(http.+?\.png)/' $OUTPUT)
echo $IMGURL
