#!/bin/sh

GRABDIR=/tmp
COUNT=$(ls "${GRABDIR}"/paste-*.txt 2>/dev/null | wc -l)
ID=$((COUNT+1))

xclip -o > "${GRABDIR}/paste-${ID}.txt"

echo -n hold on | xclip

THING="${GRABDIR}/paste-${ID}.txt"
BLAH=$(sha1sum "${THING}" | awk '{ print $1 }')

if [ -f $THING ]; then
    scp "${THING}" "pompom:scrots/${BLAH}.txt"
fi

# if scp fails, then exit
[ $? -ne 0 ] && (echo error && exit 1)

PASTEURL="http://omgren.com/s/${BLAH}.txt"

# make sure this gets into xclip and the clipboard
echo -n $PASTEURL | xclip
echo -n $PASTEURL | xclip -selection c

#done
echo read $PASTEURL into xclip
