#!/bin/bash

if [ "x$XDG_CONFIG_HOME" = "x" ]; then
  XDG_CONFIG_HOME="$HOME/.config"
fi

## load options
if [ ! -f "$XDG_CONFIG_HOME/grabbing/config" ]; then
  echo "please set up config file \"$XDG_CONFIG_HOME/grabbing/config\"" 1>&2
  exit 2
fi

source $XDG_CONFIG_HOME/grabbing/config

if [ "$#" -lt 1 -o ! -f "$1" ]; then
  echo "usage: $0 <file> [suffix]" 1>&2
  exit 1
fi

THING="$1"

# set default format
if [ "x${FORMAT}" = "x" ]; then
  FORMAT="sha1sum"
fi

# Either use sha1 or timestamp as filename on remote machine, depending on config
if [ "${FORMAT}" = "time" ]; then
  STAMP="$(date +"%Y-%m-%d_%H-%M-%S")"
  RNAME=${STAMP}
elif [ "${FORMAT}" = "sha1sum" ]; then
  RNAME=$(sha1sum "${THING}" | awk '{ print $1 }')
else
  echo "No valid name format specified, please fix config file."
  exit 3
fi

## let user specify a suffix, if not, then
## uses mtsuf script to guess suffix of file
if [ "X${2}" = "X" ]; then
  SUFFIX=$(mtsuf "${THING}")
else
  SUFFIX="${2}"
fi

if [ "X${SUFFIX}" != "X" ]; then
  RNAME="${RNAME}.${SUFFIX}"
fi

## add your options and such in the config file
if [ "${TXTDIRECTORY}" = "false" ] || [ "${SUFFIX}" != "txt" ]; then
  scp ${SCPOPTS} "${THING}" "${SSHSTR}":"${SSHDIR}/${RNAME}"
elif [ "${TXTDIRECTORY}" = "true" ] && [ "${SUFFIX}" = "txt" ]; then
  scp ${SCPOPTS} "${THING}" "${SSHSTR}":"${SSHDIRTXT}/$RNAME"
  USEDTXTDIR="true"
fi

if [ $? -ne 0 ]; then
  echo error 1>&2
  exit 1
fi

## change this to reflect your url and such in the config file
if [ "${USEDTXTDIR}" = "true" ]; then
  IMGURL="${WEBURLTXT}/${RNAME}"
else
  IMGURL="${WEBURL}/${RNAME}"
fi

echo $IMGURL
