#!/bin/sh

if [ "$#" -lt 1 -o ! -f "$1" ]; then
  echo "usage: $0 <file> [suffix]" 1>&2
  exit 1
fi

## take a file and get its sha1 to use as the file name on the remote machine. 
THING="$1"
RNAME=$(sha1sum "${THING}" | awk '{ print $1 }')

## let user specify a suffix, if not, then
## uses mtsuf script to guess suffix of file
if [ "X${2}" = "X" ]; then
  SUFFIX=$(mtsuf "${THING}")
else
  SUFFIX="${2}"
fi

if [ "X${SUFFIX}" != "X" ]; then
  RNAME="${RNAME}.${SUFFIX}"
fi

## add your options and such here
scp "${THING}" pompom:"scrots/${RNAME}"

if [ $? -ne 0 ]; then
  echo error 1>&2
  exit 1
fi

## change this to reflect your url and such
IMGURL="http://omgren.com/s/${RNAME}"
echo $IMGURL
